### ISSUE TITLE
Tracker is not updating

### ISSUE THREAD

**Issue by aquarat** [api3dao/api3-tracker#101]
The Tracker is stuck ([reported on Slack](https://api3workspace.slack.com/archives/C010HL1QXRC/p1731918684838309)).

Initial investigation:
From `/var/log/api3-logs-download.log `:
```
$ /app/node_modules/.bin/ts-node cli.ts logs download
/app/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
services/db.ts(12,8): error TS2339: Property 'prisma' does not exist on type 'typeof globalThis'.

    at createTSError (/app/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/app/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/app/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/app/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/app/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Object.require.extensions.<computed> [as .ts] (/app/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19) {
  diagnosticCodes: [ 2339 ]
}
error Command failed with exit code 1.
```

I tried adding a ts-ignore to the problematic line (as this was a compilation problem):
```typescript
import { PrismaClient } from "@prisma/client";

let prisma: PrismaClient;

if (typeof window === "undefined") {
  if (process.env.NODE_ENV === "production") {
    prisma = new PrismaClient();
  } else {
    if (!global.prisma) {
      global.prisma = new PrismaClient();
    }
    // @ts-expect-error TS2339
    ({ prisma } = global);
  }
}

// @ts-ignore
export default prisma;
```
but this just caused errors further down the line.

I think part of the problem is that the CI is probably not testing the compilation of the cron scripts because they're executed with a separate `tsconfig.cli.json` configuration.

In addition, after I fixed the downstream DB issue I then had a problem with `yargs` missing. Also, `ts-node` was missing. 

For now I've reverted the problematic PR/change: https://github.com/api3dao/api3-tracker/pull/97 via https://github.com/api3dao/api3-tracker/pull/102

**Comment by dcroote** [comment]
Strange, I will have a look. The CLI isn't tested in CI as far as I can tell (opportunity there in and of itself), but `yarn run lint:tsc` was being run, so you must be right about the separate tsconfig. Apologies overall and thanks for this debugging.

**Comment by dcroote** [comment]
I've reproduced the error inside the Docker container, now working on a fix

**Comment by dcroote** [comment]
Sooo @aquarat  you might not believe this, but it appears that the cron commands just need `--transpile-only` to be added after `ts-node` and it all works (first command without, shows your error above, second command, with, works):

![image](https://github.com/user-attachments/assets/0283bd20-df38-4d92-b496-00c695fbb087)

The reason is close to what you thought but not quite: the files are typechecked by `tsconfig.json` (`include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],`) but the cron commands are run with `tsconfig.cli.ts` and are missing all of the types.

I reverted the reverted commit in doing this.

**Comment by aquarat** [comment]
haha, typical and interesting, well done :)
