### ISSUE TITLE
API3 DAO Tracker Bug Bounty 

### ISSUE THREAD

**Issue by Ashar2shahid** [api3dao/api3-tracker#50]
### Prize Title

API3 DAO Tracker

### Prize Bounty

This is an open bounty for anybody to participate in. For every valid bug reported, no matter the size, we offer **200 API3** and will award a maximum of **8 prizes for this category**.

### Challenge Description

[API3 DAO Tracker](https://tracker.api3.org) provides a web interface to see on-chain details of the API3 DAO, including:

- Members, their stakes, shares, voting power and votings history
- Details of the votings
- All events from the smart contracts of the API3 DAO
- DAO Treasuries status

This bug bounty invites participants to help find defects on the API3 DAO Tracker. API3 is offering a monetary reward for successfully discovering and reporting a vulnerability or bug that would affect the DAO Tracker functionality that may mislead governing parties. For example, a bug might be that the parameters of a proposal are being displayed incorrectly.

You can refer to the [API3 Docs](https://docs.api3.org/dao-members/) to understand how the DAO works.

You can also clone and build the DAO Tracker locally. Refer to the [Github Repo](https://github.com/api3dao/api3-tracker).

###  Submission Process

- You are allowed to treat the [API3 Tracker](https://tracker.api3.org) as a black box and look for bugs visually or refer to [the Github Repo](https://github.com/api3dao/api3-tracker) to find the bugs at the source.

- The Bug Reporting bounty is open to all. To submit a bug, head to the [DAO Tracker’s GitHub repository](https://github.com/api3dao/api3-tracker) and submit an issue using [the Community bug bounty template.](https://github.com/api3dao/api3-tracker/issues/new/choose) (you’ll need a Github account):

### Acceptance Criteria

- You are required to follow the [Community bug bounty issue template](https://github.com/api3dao/api3-tracker/issues/new/choose). Explain each and every section briefly. Use screenshots wherever necessary. Make sure it covers all following points:
    - Steps to reproduce
    - Expected behavior
    - Current behavior
    - Screenshots (if applicable)
    - Environment
    - Potential consequences 

### Rewards

This is an open bounty for anybody to participate in. For every valid bug reported, no matter the size, we offer **200 API3** and will award a maximum of **8 prizes** for this category.

The bug bounty will run from Feb 26th through to April 30th.

### Winner Announcement Date

April 14th; two weeks after the deadline.

### Resources

- [API3 DAO Tracker](https://tracker.api3.org)
- [DAO Tracker Github Repo](https://github.com/api3dao/api3-tracker)
- [API3 DAO Dashboard](api3.org/dao)
- [API3 DAO Docs](https://docs.api3.org/dao-members/)

**Comment by en0c-026** [comment]
Gitcoin Issue is set to "Traditional", it should be "Multiple". Otherwise, it is not allowed to send a submission if someone has already done so before.
