### ISSUE TITLE
Miscalculated votes percentage in the proposal page and proposals list

### ISSUE THREAD

**Issue by Soptq** [api3dao/api3-tracker#52]
## Steps to reproduce

Go to an arbitrary proposal page, for example, proposal [60](https://tracker.api3.org/votings/60) named "CORE TECHNICAL TEAM, MAY–JULY 2022"

## Expected behavior

1. As the proposal is rejected by the DAO, there should be more voters voting "Reject" compared to voting "For".
2. The total votes percentage should equal to the sum of different voters' votes percentages.

## Current behavior

1. Although proposal 60 is rejected by the DAO, the website suggests that nobody voted "Against" and all voters voted "For".
2. The website displays a total votes percentage of "Against" equals to 0%. However, by manually summing different voters's votes percentage, the total votes percentage of "Against" should equal to 27.32%.
3. The miscalculated result is also displayed in the proposals [list](https://tracker.api3.org/votings).

## Screenshots (if applicable)

<img width="779" alt="bug2" src="https://user-images.githubusercontent.com/32592090/221425352-c315e52e-e7ca-47cd-be8c-965b5d4a8204.png">
<img width="1016" alt="bug3" src="https://user-images.githubusercontent.com/32592090/221425354-23b8d95e-e855-40fa-9b9c-2c606eb02940.png">
<img width="993" alt="bug4" src="https://user-images.githubusercontent.com/32592090/221426090-52b3921e-9ba5-4f7d-8aa6-01313d9b2d8a.png">

## Environment

1. iOS with Safari
2. macOS with Safari and Chrome

## Potential consequences

Voters might be confused about whether the proposal is executed (or rejected) and how the votes are distributed.

**Comment by Ashar2shahid** [comment]
This isn't technically a bug but I can see how it can be confusing for someone new to the DAO. Each proposal need a minimum threshold before it can be executed. @EnormousCloud is it possible to display that information ?

**Comment by dcroote** [comment]
@Ashar2shahid - while the proposal being rejected is accurate, the part that shows "Nobody voted against" at the top when in fact millions of shares voted against (see tx 2 & 3) is definitely a bug.

Also the total sum that supports is wrong and also a bug.
