### ISSUE TITLE
Incorrect calculation of gas usage and fee in VoteGas add function

### ISSUE THREAD

**Issue by en0c-026** [api3dao/api3-tracker#54]
## Steps to reproduce
N/A

## Expected behavior
When a transaction hash is added to a vote, the gasUsed and feeUsd values for that transaction should be added to any existing values for that transaction in the VoteGas.VOTES map.

## Current behavior
The existing GasUsage values are not being properly updated when a new value is added.

## Screenshots (if applicable)
https://github.com/api3dao/api3-tracker/blob/04c7c2665d829417b2046cd76fc49d735e1ac91b/services/gas.ts#L42-L50

It should be fixed like this
```javascript
    } else {
      const existing: GasUsage = VoteGas.VOTES.get(voteId)?.get(
        txHash
      ) as GasUsage;
      const updated: GasUsage = {
        gasUsed: existing.gasUsed.add(gasUsed),
        feeUsd: existing.feeUsd + feeUsd,
      };
      VoteGas.VOTES.get(voteId)?.set(txHash, updated);
    }
```

## Environment
N/A

## Potential consequences
If this issue is not resolved, incorrect gas usage and fee data could be reported for votes in the VoteGas.totals() function. This could potentially lead to incorrect decisions being made based on the reported data.

**Comment by Ashar2shahid** [comment]
Thanks for the submission @en0c-026, will review it and let you know on the 15th

**Comment by EnormousCloud** [comment]
> on first glance this seems like a valid bug, @EnormousCloud can you chime in ?

yes, this was absolutely valid point

**Comment by en0c-026** [comment]
> > on first glance this seems like a valid bug, @EnormousCloud can you chime in ?
> 
> yes, this was absolutely valid point

Let me know if you need my email or my discord handle to arrange the payment of the reward. thanks

**Comment by en0c-026** [comment]
@Ashar2shahid I sent you a friend request on Discord

**Comment by KenCarvAPI** [comment]
Hi @en0c-026 if you haven't already could you send myself or Ashar your wallet address 
Feel free to DM via TG @ KenKarvez

**Comment by KenCarvAPI** [comment]
Hi @en0c-026 if you haven't already could you send myself or Ashar your wallet address. If you and Ashar haven't connected you can also message me via TG @ kenkarvez
