### ISSUE TITLE
MetaMask access

### ISSUE THREAD

**Issue by KnoxMitchell** [api3dao/api3-tracker#63]
## Steps to reproduce

_What did you do before encountering the issue?_
I used the procedure I used to stake my tokens
## Expected behavior

_What did you expect to happen?_
I expected to use the same procedure to access them

## Current behavior

_What happened?_
Connect Wallet does not show the MetaMast wallet as it does in the tutorial

## Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/129623399/230169274-b9bdaf3f-9e2a-44cb-ac9e-11a6b1d5d678.png)

_Can you show us?_
above
## Environment

_What OS and browser/app were you using?_
Foxfire, Windows 10
## Potential consequences
I cannot access my staked tokens
_What is the worst that can happen because of this? Is this actually a bug in functionality?_
Above

**Comment by dcroote** [comment]
@KnoxMitchell in your Environment you say Firefox, but your screenshot it appears to be of Microsoft Edge?

**Comment by KnoxMitchell** [comment]
Hi Derek,

You are correct.

I started with Firefox and I guess my computer guys switched me over.

Sorry about not recognizing that!

Thank you.

Knox Mitchell
________________________________

**Comment by dcroote** [comment]
No problem!

**Comment by KnoxMitchell** [comment]
Hi Derek,

I should have mentioned that I was seriously hacked and during clean up my email box was changed for protection.

My legal name is Knox Marquand Mitchell

Sorry, forgot about that!

Knox M Mitchell
________________________________

**Comment by KnoxMitchell** [comment]
Hi Derek,

Pretty hard to empty my account as requested when you will not allow me access!

I deactivated my account recently when seriously hacked and I have been trying since January '23 to reactivate my account, especially now with your announcement!

My browser is Bing, Microsoft, and my email box is ***@***.***, changed from ***@***.*** after I was recently seriously hacked. If I need to revert to ***@***.***, I will need to contact my computer guys to see what that entails.

My legal name is Knox Marquand Mitchell!

I have sent a selfie with my blurry Official Florida ID card and an iPhone clearer picture of my ID card.

What do I need to repeat and to what address?

Please, to meet your deadline!

Thank you!

Knox Marquand Mitchell



________________________________

**Comment by dcroote** [comment]
Hi Knox,

I'm not sure who you're corresponding with or what you're referencing, but please avoid sharing personal information, especially in a public forum such as this.

**Comment by KnoxMitchell** [comment]
Hi Derek,

How can I correspond with you, especially the above to reactivate my account to withdraw as requested?

Knox Mitchell
________________________________

**Comment by dcroote** [comment]
Hi Knox,

For support please reach out through one of our dedicated channels at https://api3.org/contact

Best,
Derek
