### ISSUE TITLE
Bug fix in main/services/gas.ts

### ISSUE THREAD

**Issue by kzhunter** [api3dao/api3-tracker#65]
## Steps to reproduce

The updated GasUsage object is not added to the VOTES map.

https://github.com/api3dao/api3-tracker/blob/main/services/gas.ts
line 42-49 else clause 

## Fix

Available in https://github.com/kzhunter/temp/blob/main/services/gas.ts
Added line 50: VoteGas.VOTES.get(voteId)?.set(txHash, updated);

## Potential consequences

Possible incorrect gas usage calculation

**Comment by Ashar2shahid** [comment]
Thank you for taking the time to submit this, however this has already been brought up in #54.
