### ISSUE TITLE
Inconsistency in Member Count on the Homepage and RewardsPage

### ISSUE THREAD

**Issue by hxrii** [api3dao/api3-tracker#66]
Inconsistency in member count on [HomePage](https://tracker.api3.org/) and [RewardsPage](https://tracker.api3.org/rewards)

## Steps to reproduce

Go over to the [HomePage](https://tracker.api3.org/) and watch the current member count

<img width="1439" alt="Screenshot 2023-04-12 at 12 56 09 PM" src="https://user-images.githubusercontent.com/70883415/231383346-eaf57472-51e6-448a-9ce7-dbf22dcdae84.png">

The count of current member is displayed as 6485

Go over to the [RewardsPage](https://tracker.api3.org/rewards) and watch the member count

<img width="1439" alt="Screenshot 2023-04-12 at 12 58 07 PM" src="https://user-images.githubusercontent.com/70883415/231383859-9a74d557-eed7-4785-a0ed-fa470851223e.png">

The count of member is displayed as 6532

## Expected behavior

Count of members in [HomePage](https://tracker.api3.org/) and [RewardsPage](https://tracker.api3.org/rewards) to be equal and consistent.

## Current behavior

The values of member count in [HomePage](https://tracker.api3.org/) and [RewardsPage](https://tracker.api3.org/rewards) are not equal(inconsistent).

## Screenshots (if applicable)

<img width="1439" alt="Screenshot 2023-04-12 at 1 03 08 PM" src="https://user-images.githubusercontent.com/70883415/231385197-3a5e3048-c756-44fb-b7c9-881dd4709ad0.png">

<img width="1439" alt="Screenshot 2023-04-12 at 1 03 21 PM" src="https://user-images.githubusercontent.com/70883415/231385268-0a14f4d6-2468-4fec-beb0-57308f9cd119.png">

## Environment

OS: Mac OS 13.2.1
Browser: Mozilla Firefox

## Potential consequences

Users visiting the website will view inconsistent number of members in each page. This can lead to confusion and eventually leading to lack of trust for the platform due inconsistency.

**Comment by KenCarvAPI** [comment]
@EnormousCloud - just checking here there isn't an intentional reason for this, e.g redundant / empty wallets do not show on the homepage.

**Comment by EnormousCloud** [comment]
@KenCarvAPI 
- Rewards page table counts total amount of all addresses interacted with smart contracts till the moment of reward.
- Home page specifically says `current members` to mark that is this number is different and it includes only who is left with non-zero balance.

So yes, its kind of intentional, but obviously the naming could be clarifying it better.
The history behind that is that Home page was cleaned up to reflect only real members

**Comment by hxrii** [comment]
So, shall I close the issue ?

**Comment by EnormousCloud** [comment]
yes, its safe to say so
